Repository Kernel360/hackerthon5-TANGTANGTANG, pull requests merged in 2025-05, with the labels that each got.

#2 Spring Project 생성
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/org/kernel360/tang/TangApplication.java
  be/src/main/resources/application.yml
  be/src/test/java/org/kernel360/tang/TangApplicationTests.java
  be/tang/.idea/workspace.xml
Labels: enhancement

#4 chore: docker-compose 를 이용한 mysql 초기화 및 mybatis 설정
  be/.gitignore
  be/build.gradle
  be/docker-compose.yml
  be/mysql/init/create_table.sql
  be/src/main/resources/application.yml
  be/tang/.idea/workspace.xml
Labels: enhancement

#15 [Feature] 공통 예외 코드 작성
  be/src/main/java/org/kernel360/tang/common/AppErrorResponse.java
  be/src/main/java/org/kernel360/tang/common/AppException.java
  be/src/main/java/org/kernel360/tang/common/AppExceptionAdvice.java
  be/src/main/java/org/kernel360/tang/common/CommonExceptionCode.java
  be/src/main/java/org/kernel360/tang/common/ExceptionCode.java
  be/src/main/java/org/kernel360/tang/common/LoggingLevel.java
  be/src/test/java/org/kernel360/tang/common/AppExceptionAdviceTest.java
Labels: enhancement

#19 [FIX] AppException의 생성자 public으로 수정
  be/src/main/java/org/kernel360/tang/common/AppException.java
Labels: bug

#17 [Feature] 회원 - 로그인
  be/build.gradle
  be/src/main/java/org/kernel360/tang/auth/AuthController.java
  be/src/main/java/org/kernel360/tang/auth/AuthService.java
  be/src/main/java/org/kernel360/tang/auth/dto/LoginRequest.java
  be/src/main/java/org/kernel360/tang/auth/dto/LoginResponse.java
  be/src/main/java/org/kernel360/tang/common/AuthExceptionCode.java
  be/src/main/java/org/kernel360/tang/config/SecurityConfig.java
  be/src/main/java/org/kernel360/tang/member/Member.java
  be/src/main/java/org/kernel360/tang/member/MemberMapper.java
  be/src/main/resources/mapper/MemberMapper.xml
Labels: enhancement

#16 [Feature] 날짜 지정 조회(단일 좌석) 기능 추가
  be/src/main/java/org/kernel360/tang/seat/AvailableSeatDto.java
  be/src/main/java/org/kernel360/tang/seat/AvailableSeatResponse.java
  be/src/main/java/org/kernel360/tang/seat/SeatController.java
  be/src/main/java/org/kernel360/tang/seat/SeatMapper.java
  be/src/main/java/org/kernel360/tang/seat/SeatService.java
  be/src/main/resources/mapper/SeatMapper.xml
Labels: enhancement

#20 [Feature] 기간 지정 조회(전체 좌석) 기능 추가
  be/src/main/java/org/kernel360/tang/seat/AvailableSeatDto.java
  be/src/main/java/org/kernel360/tang/seat/AvailableSeatIdResponse.java
  be/src/main/java/org/kernel360/tang/seat/SeatController.java
  be/src/main/java/org/kernel360/tang/seat/SeatExceptionCode.java
  be/src/main/java/org/kernel360/tang/seat/SeatMapper.java
  be/src/main/java/org/kernel360/tang/seat/SeatService.java
  be/src/main/resources/mapper/SeatMapper.xml
Labels: enhancement

#25 [Feature] 회원 - 회원 가입
  be/src/main/java/org/kernel360/tang/auth/AuthController.java
  be/src/main/java/org/kernel360/tang/auth/AuthService.java
  be/src/main/java/org/kernel360/tang/auth/MemberDto.java
  be/src/main/java/org/kernel360/tang/member/MemberMapper.java
  be/src/main/resources/mapper/MemberMapper.xml
Labels: enhancement

#28 [Feature] 실제 인증 멤버 정보 적용
  be/src/main/java/org/kernel360/tang/seat/SeatController.java
  be/src/main/java/org/kernel360/tang/seatReservation/SeatReservationController.java
Labels: enhancement

#30 [Docs] README 작성
  README.md
  img/architecture_diagram.png
  img/erd.png
Labels: documentation
